// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecieptHub.BAL.Data;

#nullable disable

namespace RecieptHub.Migrations
{
    [DbContext(typeof(RecieptHubContext))]
    [Migration("20260202190911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecieptHub.BAL.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CalculatedCalories")
                        .HasColumnType("real");

                    b.Property<float>("CalculatedCarbohydrates")
                        .HasColumnType("real");

                    b.Property<float>("CalculatedFats")
                        .HasColumnType("real");

                    b.Property<float>("CalculatedProteins")
                        .HasColumnType("real");

                    b.Property<int>("CookTime")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recipe")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.DishIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CaloriesInDish")
                        .HasColumnType("real");

                    b.Property<float>("CarbohydratesInDish")
                        .HasColumnType("real");

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<float>("FatsInDish")
                        .HasColumnType("real");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<float>("ProteinsInDish")
                        .HasColumnType("real");

                    b.Property<float>("QuantityGrams")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DishIngredients");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<float>("Carbohydrates")
                        .HasColumnType("real");

                    b.Property<float>("Fats")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Proteins")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyMenuDayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("WeeklyMenuDayId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.WeeklyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("WeeklyMenus");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.WeeklyMenuDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BreakfastMealId")
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int?>("DinnerMealId")
                        .HasColumnType("integer");

                    b.Property<int?>("LunchMealId")
                        .HasColumnType("integer");

                    b.Property<int?>("SnackMealId")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyMenuId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BreakfastMealId")
                        .IsUnique();

                    b.HasIndex("DinnerMealId")
                        .IsUnique();

                    b.HasIndex("LunchMealId")
                        .IsUnique();

                    b.HasIndex("SnackMealId")
                        .IsUnique();

                    b.HasIndex("WeeklyMenuId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WeeklyMenuDays");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.DishIngredient", b =>
                {
                    b.HasOne("RecieptHub.BAL.Models.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecieptHub.BAL.Models.Ingredient", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.Meal", b =>
                {
                    b.HasOne("RecieptHub.BAL.Models.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RecieptHub.BAL.Models.WeeklyMenuDay", "WeeklyMenuDay")
                        .WithMany()
                        .HasForeignKey("WeeklyMenuDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("WeeklyMenuDay");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.WeeklyMenuDay", b =>
                {
                    b.HasOne("RecieptHub.BAL.Models.Meal", "BreakfastMeal")
                        .WithOne()
                        .HasForeignKey("RecieptHub.BAL.Models.WeeklyMenuDay", "BreakfastMealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RecieptHub.BAL.Models.Meal", "DinnerMeal")
                        .WithOne()
                        .HasForeignKey("RecieptHub.BAL.Models.WeeklyMenuDay", "DinnerMealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RecieptHub.BAL.Models.Meal", "LunchMeal")
                        .WithOne()
                        .HasForeignKey("RecieptHub.BAL.Models.WeeklyMenuDay", "LunchMealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RecieptHub.BAL.Models.Meal", "SnackMeal")
                        .WithOne()
                        .HasForeignKey("RecieptHub.BAL.Models.WeeklyMenuDay", "SnackMealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RecieptHub.BAL.Models.WeeklyMenu", "WeeklyMenu")
                        .WithMany("WeeklyMenuDays")
                        .HasForeignKey("WeeklyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BreakfastMeal");

                    b.Navigation("DinnerMeal");

                    b.Navigation("LunchMeal");

                    b.Navigation("SnackMeal");

                    b.Navigation("WeeklyMenu");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.Dish", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.Ingredient", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("RecieptHub.BAL.Models.WeeklyMenu", b =>
                {
                    b.Navigation("WeeklyMenuDays");
                });
#pragma warning restore 612, 618
        }
    }
}
